export enum Environment {
    PROD = 'prod',
    STAGING = 'staging',
    AUTOMATION = 'automation',
    TEST = 'test',
    DEV = 'dev',
    LOCAL = 'local',
}

export const EnvironmentAlt = {
    p: Environment.PROD,
    live: Environment.PROD,
    production: Environment.PROD,
    s: Environment.STAGING,
    stage: Environment.STAGING,
    model: Environment.STAGING,
    preprod: Environment.STAGING,
    preproduction: Environment.STAGING,
    demo: Environment.STAGING,
    external: Environment.STAGING,
    pipeline: Environment.AUTOMATION,
    git: Environment.AUTOMATION,
    github: Environment.AUTOMATION,
    gitlab: Environment.AUTOMATION,
    bitbucket: Environment.AUTOMATION,
    jenkins: Environment.AUTOMATION,
    t: Environment.TEST,
    q: Environment.TEST,
    testing: Environment.TEST,
    internal: Environment.TEST,
    qc: Environment.TEST,
    qa: Environment.TEST,
    d: Environment.DEV,
    development: Environment.DEV,
    trunk: Environment.DEV,
    sandbox: Environment.DEV,
}

export enum HttpMethod {
    GET = 'get',
    POST = 'post',
    PUT = 'put',
    PATCH = 'patch',
    DELETE = 'delete',
    HEAD = 'head',
    OPTIONS = 'options',
    PURGE = 'purge',
    LINK = 'link',
    UNLINK = 'unlink',
}
export enum Severity {
    ERROR = 'error',
    WARN = 'warn',
    LOG = 'log',
    INFO = 'info',
    TRACE = 'trace',
    DEBUG = 'debug',
}
export enum ProcessorKey {
    FIRST = 'first',
    CREATED = 'created',
    INITIALIZED = 'initialized',
    APPLICATION = 'application',
    ROUTER_CREATED = 'router-created',
    PRE_HANDLERS = 'pre-handlers',
    POST_HANDLERS  ='post-handlers',
    END = 'end',
    RESERVED_0 = 'reserved-0',
    RESERVED_1 = 'reserved-1',
    RESERVED_2 = 'reserved-2',
    RESERVED_3 = 'reserved-3',
    RESERVED_4 = 'reserved-4',
    RESERVED_5 = 'reserved-5',
    RESERVED_6 = 'reserved-6',
    RESERVED_7 = 'reserved-7',
    RESERVED_8 = 'reserved-8',
    RESERVED_9 = 'reserved-9'
}
